version: '3.8'

services:
  gui-app:
    build:
      context: ./gui-app
      args:
        GUI_USER: "${GUI_USER}"
        GUI_GROUP: "${GUI_GROUP}"
        GUI_UID: "${GUI_UID}"
        GUI_GID: "${GUI_GID}"
        AUTO_MCS_URL: "${AUTO_MCS_URL}"
    image: "${PROJECT_NAME}:latest"
    container_name: "${PROJECT_NAME}-gui-container"
    env_file:
      - .env
    expose:
      - ${VNC_PORT}
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

  guacd:
    image: guacamole/guacd:1.5.4
    container_name: "${PROJECT_NAME}-guacd"
    expose:
      - 4822
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole:1.5.4
    container_name: "${PROJECT_NAME}-guacamole"
    depends_on:
      - guacd
      - db
    env_file:
      - .env
    ports:
      - "${GUACAMOLE_PORT}:8080"
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_DB_USER}"
      MYSQL_PASSWORD: "${MYSQL_DB_PASSWORD}"
    volumes:
      # Mount the JDBC auth extension and MySQL driver
      - ./extensions:/etc/guacamole/extensions:ro
      - ./lib:/etc/guacamole/lib:ro
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: "${PROJECT_NAME}-db"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_DB_USER}"
      MYSQL_PASSWORD: "${MYSQL_DB_PASSWORD}"
    volumes:
      # Init schema + admin user on first run
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
      # Persist the database data
      - ${VOLUME_DB_DATA}:/var/lib/mysql
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

networks:
  ${NETWORK_NAME}:
    driver: bridge

volumes:
  ${VOLUME_DB_DATA}:
