version: "3.8"

services:

  # 1) MySQL for Guacamole authentication
  guacamole-db:
    image: mysql:8.0
    container_name: guacamole-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guac_pass123
    volumes:
      - guac_db_data:/var/lib/mysql
    networks:
      - guacnet

  # 2) Guacamole daemon
  guacd:
    image: guacamole/guacd
    container_name: guacd
    networks:
      - guacnet

  # 3) Guacamole web app, hooked up to MySQL above
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    depends_on:
      - guacamole-db
      - guacd
    environment:
      MYSQL_HOSTNAME: guacamole-db
      MYSQL_PORT:     3306
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER:     guacamole_user
      MYSQL_PASSWORD: guac_pass123
    ports:
      - "9000:8080"
    networks:
      - guacnet

  # 4) Your Auto-MCS VNC+GUI container
  automcs:
    build:
      context: .
      args:
        AUTO_MCS_VERSION: ${AUTO_MCS_VERSION:-2.3}
    image: ${IMAGE_NAME:-auto-mcs-webgui}:${IMAGE_TAG:-latest}
    container_name: automcs
    environment:
      # VNC password passed into the container
      VNC_PASSWORD: ${VNC_PASSWORD:-changeme}
    ports:
      - "5900:5900"
    networks:
      - guacnet

volumes:
  guac_db_data:

networks:
  guacnet:
    driver: bridge
