version: '3.8'

services:
  gui-container:
    build:
      context: ./gui-container
      args:
        AUTO_MCS_URL: "${AUTO_MCS_URL}"
    image: "${PROJECT_NAME}:latest"
    container_name: "${PROJECT_NAME}-gui-container"
    env_file:
      - .env
    expose:
      - 5900
    networks:
      - appnet
    restart: unless-stopped

  guacd:
    image: guacamole/guacd:1.5.4
    container_name: "${PROJECT_NAME}-guacd"
    expose:
      - 4822
    networks:
      - appnet
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole:1.5.4
    container_name: "${PROJECT_NAME}-guacamole"
    depends_on:
      - guacd
      - db
    env_file:
      - .env
    ports:
      - "${GUACAMOLE_PORT}:8080"  
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT:     4822
      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER:     "${MYSQL_DB_USER}"
      MYSQL_PASSWORD: "${MYSQL_DB_PASSWORD}"
    volumes:
      - ./extensions:/etc/guacamole/extensions:ro
      - ./lib:/etc/guacamole/lib:ro
    networks:
      - appnet
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: "${PROJECT_NAME}-db"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE:      "${MYSQL_DB_NAME}"
      MYSQL_USER:          "${MYSQL_DB_USER}"
      MYSQL_PASSWORD:      "${MYSQL_DB_PASSWORD}"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/mysql
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    name: "${NETWORK_NAME}"  
    driver: bridge

volumes:
  db_data:
    name: "${VOLUME_DB_DATA}" 
