version: '3.8'

services:
  automcs:
    build:
      context: .                 # Directory with your Dockerfile
      dockerfile: Dockerfile
    container_name: auto-mcs
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD}  # Set via `export VNC_PASSWORD=…`
    volumes:
      - auto-mcs-data:/data      # ← matches the “auto-mcs-data” volume below
    expose:
      - "5900"                   # VNC port for Guacamole to connect
    restart: unless-stopped

  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    depends_on:
      - guacd
      - automcs
    environment:
      GUACD_HOSTNAME: guacd      # guacd service host
      GUACD_PORT: 4822
    ports:
      - "9000:8080"              # Exposes Guacamole UI on host:9000
    volumes:
      - guacamole-config:/etc/guacamole  # ← matches the “guacamole-config” volume below
    restart: unless-stopped

# Named volumes must be defined exactly as referenced above:
volumes:
  auto-mcs-data:
    name: auto-mcs_data
  guacamole-config:
    name: guacamole_config

# (Optional) Explicit network naming—Compose will create this for you:
networks:
  default:
    name: automcs_network
